/* Planline built-in man-hour norms library (version 2).
   INDICATIVE planning values only: man-hours per unit for direct craft labour (engineering and
   procurement items are office man-hours). They are compiled from typical published estimating
   ranges (e.g. Page, Richardson, NECA/MCAA-style unit rates and common EPC contractor norms) and
   rounded to avoid false precision. Productivity varies widely by country, site, crew, method and
   access; calibrate these figures to your own records. The library is fully editable in the app.
   Entry ids are stable: saved projects reference norms by id. */
window.PS = window.PS || {};
window.PS.NORMS_VERSION = 2;

window.PS.DEFAULT_NORMS = [

  // ===== Oil & gas (EPCM) =====
  // Piping fabrication (shop)
  { id: 'bw-shop-cs-std', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, CS, STD (shop)', unit: 'inch-dia', mh: 0.7 },
  { id: 'bw-shop-cs-xs', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, CS, XS / Sch 80 (shop)', unit: 'inch-dia', mh: 0.94 },
  { id: 'bw-shop-cs-160', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, CS, Sch 160 (shop)', unit: 'inch-dia', mh: 1.4 },
  { id: 'bw-shop-ss-std', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, SS, STD (shop)', unit: 'inch-dia', mh: 0.98 },
  { id: 'bw-shop-ss-xs', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, SS, XS / Sch 80 (shop)', unit: 'inch-dia', mh: 1.3 },
  { id: 'bw-shop-ss-160', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, SS, Sch 160 (shop)', unit: 'inch-dia', mh: 2 },
  { id: 'bw-shop-as-std', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, alloy/Cr-Mo, STD (shop)', unit: 'inch-dia', mh: 1.3 },
  { id: 'bw-shop-as-xs', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, alloy/Cr-Mo, XS / Sch 80 (shop)', unit: 'inch-dia', mh: 1.7 },
  { id: 'bw-shop-as-160', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, alloy/Cr-Mo, Sch 160 (shop)', unit: 'inch-dia', mh: 2.5 },
  { id: 'bw-shop-dx-std', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, duplex, STD (shop)', unit: 'inch-dia', mh: 1.5 },
  { id: 'bw-shop-dx-xs', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, duplex, XS / Sch 80 (shop)', unit: 'inch-dia', mh: 2 },
  { id: 'bw-shop-dx-160', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Butt weld, duplex, Sch 160 (shop)', unit: 'inch-dia', mh: 2.9 },
  { id: 'sw-shop-cs', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Socket weld, CS (shop)', unit: 'inch-dia', mh: 0.45 },
  { id: 'sw-shop-ss', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Socket weld, SS (shop)', unit: 'inch-dia', mh: 0.63 },
  { id: 'cut-bevel-shop', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Cut and bevel, CS (shop)', unit: 'inch-dia', mh: 0.25 },
  { id: 'branch-shop', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Branch / olet connection, CS (shop)', unit: 'inch-dia', mh: 1 },
  { id: 'spool-fab-shop', sector: 'Oil & gas (EPCM)', cat: 'Piping fabrication (shop)', name: 'Spool fabrication all-in, CS (shop)', unit: 'inch-dia', mh: 1.8 },
  // Welding & NDT
  { id: 'pipe-weld', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, CS, STD (field)', unit: 'inch-dia', mh: 1.2 },
  { id: 'bw-fld-cs-xs', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, CS, XS / Sch 80 (field)', unit: 'inch-dia', mh: 1.6 },
  { id: 'bw-fld-cs-160', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, CS, Sch 160 (field)', unit: 'inch-dia', mh: 2.4 },
  { id: 'bw-fld-ss-std', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, SS, STD (field)', unit: 'inch-dia', mh: 1.7 },
  { id: 'bw-fld-ss-xs', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, SS, XS / Sch 80 (field)', unit: 'inch-dia', mh: 2.3 },
  { id: 'bw-fld-ss-160', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, SS, Sch 160 (field)', unit: 'inch-dia', mh: 3.4 },
  { id: 'bw-fld-as-std', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, alloy/Cr-Mo, STD (field)', unit: 'inch-dia', mh: 2.2 },
  { id: 'bw-fld-as-xs', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, alloy/Cr-Mo, XS / Sch 80 (field)', unit: 'inch-dia', mh: 2.9 },
  { id: 'bw-fld-as-160', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, alloy/Cr-Mo, Sch 160 (field)', unit: 'inch-dia', mh: 4.3 },
  { id: 'bw-fld-dx-std', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, duplex, STD (field)', unit: 'inch-dia', mh: 2.5 },
  { id: 'bw-fld-dx-xs', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, duplex, XS / Sch 80 (field)', unit: 'inch-dia', mh: 3.4 },
  { id: 'bw-fld-dx-160', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Butt weld, duplex, Sch 160 (field)', unit: 'inch-dia', mh: 5 },
  { id: 'sw-fld-cs', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Socket weld, CS (field)', unit: 'inch-dia', mh: 0.75 },
  { id: 'sw-fld-ss', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Socket weld, SS (field)', unit: 'inch-dia', mh: 1 },
  { id: 'ndt-rt-film', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Radiography (RT), per film', unit: 'sheet', mh: 0.6 },
  { id: 'ndt-rt-s', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Radiography (RT), joint up to 6"', unit: 'joint', mh: 1.2 },
  { id: 'ndt-rt-l', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Radiography (RT), joint 8" to 24"', unit: 'joint', mh: 3 },
  { id: 'ndt-ut', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Ultrasonic test (UT), per joint', unit: 'joint', mh: 1.5 },
  { id: 'ndt-pt', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Dye penetrant test (PT), per joint', unit: 'joint', mh: 0.5 },
  { id: 'ndt-mt', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Magnetic particle test (MT), per joint', unit: 'joint', mh: 0.6 },
  { id: 'ndt-pmi', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'Positive material identification (PMI)', unit: 'point', mh: 0.25 },
  { id: 'pwht-2', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'PWHT, 2" joint (local heat treatment)', unit: 'joint', mh: 3 },
  { id: 'pwht-6', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'PWHT, 6" joint (local heat treatment)', unit: 'joint', mh: 5 },
  { id: 'pwht-12', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'PWHT, 12" joint (local heat treatment)', unit: 'joint', mh: 8 },
  { id: 'pwht-24', sector: 'Oil & gas (EPCM)', cat: 'Welding & NDT', name: 'PWHT, 24" joint (local heat treatment)', unit: 'joint', mh: 14 },
  // Piping erection
  { id: 'pipe-erect', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe erection, up to 6" (average)', unit: 'm', mh: 1.5 },
  { id: 'pipe-erect-l', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe erection, 8" to 16" (average)', unit: 'm', mh: 3.5 },
  { id: 'pipe-erect-sb', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Small-bore pipe erection, up to 1-1/2"', unit: 'm', mh: 0.6 },
  { id: 'pipe-hdl-2', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 2" NPS', unit: 'm', mh: 0.8 },
  { id: 'pipe-hdl-4', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 4" NPS', unit: 'm', mh: 1.2 },
  { id: 'pipe-hdl-6', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 6" NPS', unit: 'm', mh: 1.6 },
  { id: 'pipe-hdl-8', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 8" NPS', unit: 'm', mh: 2 },
  { id: 'pipe-hdl-12', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 12" NPS', unit: 'm', mh: 3 },
  { id: 'pipe-hdl-16', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 16" NPS', unit: 'm', mh: 3.8 },
  { id: 'pipe-hdl-20', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 20" NPS', unit: 'm', mh: 4.8 },
  { id: 'pipe-hdl-24', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 24" NPS', unit: 'm', mh: 5.8 },
  { id: 'pipe-hdl-36', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe handling and erection, 36" NPS', unit: 'm', mh: 9 },
  { id: 'spool-erect', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Spool erection, prefabricated', unit: 'MT', mh: 25 },
  { id: 'valve', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Valve installation, up to 6" (average)', unit: 'each', mh: 2.5 },
  { id: 'valve-sb', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Valve, screwed / socket weld, up to 1-1/2"', unit: 'each', mh: 1 },
  { id: 'valve-man-2', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Manual valve, flanged, 2"', unit: 'each', mh: 1.5 },
  { id: 'valve-man-6', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Manual valve, flanged, 6"', unit: 'each', mh: 4.5 },
  { id: 'valve-man-12', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Manual valve, flanged, 12"', unit: 'each', mh: 10 },
  { id: 'valve-man-24', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Manual valve, flanged, 24"', unit: 'each', mh: 30 },
  { id: 'valve-mov-4', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Motor-operated valve (MOV), 4"', unit: 'each', mh: 10 },
  { id: 'valve-mov-8', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Motor-operated valve (MOV), 8"', unit: 'each', mh: 18 },
  { id: 'valve-mov-16', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Motor-operated valve (MOV), 16"', unit: 'each', mh: 30 },
  { id: 'valve-psv', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pressure safety valve, up to 4"', unit: 'each', mh: 6 },
  { id: 'bolt-2', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Flanged joint bolt-up, 2"', unit: 'joint', mh: 1 },
  { id: 'bolt-6', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Flanged joint bolt-up, 6"', unit: 'joint', mh: 2 },
  { id: 'bolt-12', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Flanged joint bolt-up, 12"', unit: 'joint', mh: 4 },
  { id: 'bolt-24', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Flanged joint bolt-up, 24"', unit: 'joint', mh: 9 },
  { id: 'bolt-torque', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Controlled torquing / tensioning, per joint', unit: 'joint', mh: 3 },
  { id: 'support', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pipe supports, fabricate and fix', unit: 'kg', mh: 0.12 },
  { id: 'support-std', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Standard support (shoe, guide, clamp)', unit: 'each', mh: 2.5 },
  { id: 'support-spring', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Spring hanger / variable support', unit: 'each', mh: 8 },
  { id: 'hydro', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Hydrotest and flushing (average)', unit: 'm', mh: 0.12 },
  { id: 'pneu-test', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Pneumatic test', unit: 'm', mh: 0.1 },
  { id: 'flush', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Water flushing', unit: 'm', mh: 0.08 },
  { id: 'reinstate', sector: 'Oil & gas (EPCM)', cat: 'Piping erection', name: 'Reinstatement after test, per test pack', unit: 'each', mh: 16 },
  // Mechanical equipment
  { id: 'pump', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Pump set installation and alignment (average)', unit: 'each', mh: 40 },
  { id: 'pump-s', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Pump set, motor up to 15 kW', unit: 'each', mh: 30 },
  { id: 'pump-m', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Pump set, motor 15 to 75 kW', unit: 'each', mh: 50 },
  { id: 'pump-l', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Pump set, motor 75 to 250 kW', unit: 'each', mh: 90 },
  { id: 'pump-xl', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Pump set, motor above 250 kW', unit: 'each', mh: 160 },
  { id: 'pump-vert', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Vertical can / turbine pump', unit: 'each', mh: 120 },
  { id: 'comp-cent', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Centrifugal compressor train', unit: 'MT', mh: 30 },
  { id: 'comp-recip', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Reciprocating compressor', unit: 'MT', mh: 35 },
  { id: 'static-eq', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Static equipment erection (average)', unit: 'MT', mh: 12 },
  { id: 'vessel-h', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Horizontal vessel / drum', unit: 'MT', mh: 10 },
  { id: 'column', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Column / tower, single lift', unit: 'MT', mh: 14 },
  { id: 'column-dress', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Column dressing (platforms, ladders)', unit: 'MT', mh: 40 },
  { id: 'hx-st', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Shell-and-tube exchanger', unit: 'MT', mh: 12 },
  { id: 'hx-bundle', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Exchanger bundle pull / reinsert', unit: 'each', mh: 24 },
  { id: 'air-cooler', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Air-cooled exchanger, assembly and erection', unit: 'MT', mh: 20 },
  { id: 'heater', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Fired heater, erection', unit: 'MT', mh: 45 },
  { id: 'refractory', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Refractory castable lining', unit: 'm³', mh: 30 },
  { id: 'skid', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Packaged skid', unit: 'MT', mh: 8 },
  { id: 'trays-s', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Column trays, up to 2 m diameter', unit: 'each', mh: 6 },
  { id: 'trays-l', sector: 'Oil & gas (EPCM)', cat: 'Mechanical equipment', name: 'Column trays, above 2 m diameter', unit: 'each', mh: 12 },
  // Tanks
  { id: 'tank-bottom', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'API 650 bottom plates, lay and weld', unit: 'MT', mh: 22 },
  { id: 'tank-shell', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'API 650 shell plates, erect and weld', unit: 'MT', mh: 30 },
  { id: 'tank-roof-fix', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'Fixed cone roof incl. structure', unit: 'MT', mh: 35 },
  { id: 'tank-roof-float', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'Floating roof (external / internal)', unit: 'MT', mh: 50 },
  { id: 'tank-noz-s', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'Tank nozzle, up to 6"', unit: 'each', mh: 6 },
  { id: 'tank-noz-l', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'Tank nozzle, 8" and above', unit: 'each', mh: 14 },
  { id: 'tank-manway', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'Tank manway', unit: 'each', mh: 10 },
  { id: 'tank-stair', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'Spiral stairway and platforms', unit: 'MT', mh: 45 },
  { id: 'tank-vacbox', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'Vacuum box test of bottom welds', unit: 'm', mh: 0.1 },
  { id: 'tank-hydro', sector: 'Oil & gas (EPCM)', cat: 'Tanks', name: 'Tank hydrotest, fill, hold and drain', unit: 'each', mh: 80 },
  // Electrical
  { id: 'cable', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Power cable laying, up to 4C x 95 mm²', unit: 'm', mh: 0.15 },
  { id: 'cable-lv-s', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'LV cable laying, up to 4C x 16 mm²', unit: 'm', mh: 0.08 },
  { id: 'cable-lv-l', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'LV cable laying, 4C x 120 to 240 mm²', unit: 'm', mh: 0.25 },
  { id: 'cable-ctrl', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Control cable laying', unit: 'm', mh: 0.06 },
  { id: 'cable-hv11', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'HV cable, 6.6 / 11 kV, 3C x 95 to 240 mm²', unit: 'm', mh: 0.35 },
  { id: 'cable-term', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'LV cable termination (average)', unit: 'each', mh: 1.5 },
  { id: 'term-lv-s', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Gland and terminate LV cable, up to 16 mm²', unit: 'each', mh: 1 },
  { id: 'term-lv-m', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Gland and terminate LV cable, 25 to 95 mm²', unit: 'each', mh: 2 },
  { id: 'term-lv-l', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Gland and terminate LV cable, 120 to 240 mm²', unit: 'each', mh: 3.5 },
  { id: 'term-hv11', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'HV termination kit, 11 kV', unit: 'each', mh: 8 },
  { id: 'tray', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Cable tray installation (average)', unit: 'm', mh: 0.6 },
  { id: 'tray-150', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Cable tray, 150 mm wide', unit: 'm', mh: 0.4 },
  { id: 'tray-600', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Cable tray, 600 mm wide', unit: 'm', mh: 0.9 },
  { id: 'conduit', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Conduit with wiring', unit: 'm', mh: 0.35 },
  { id: 'earthing', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Earthing strip / conductor', unit: 'm', mh: 0.3 },
  { id: 'earth-pit', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Earth pit with electrode', unit: 'each', mh: 6 },
  { id: 'tx-s', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Transformer, up to 500 kVA', unit: 'each', mh: 30 },
  { id: 'tx-m', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Transformer, 1 to 2.5 MVA', unit: 'each', mh: 60 },
  { id: 'tx-l', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Transformer, 5 to 10 MVA', unit: 'each', mh: 150 },
  { id: 'tx-xl', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Transformer, 20 to 40 MVA', unit: 'each', mh: 350 },
  { id: 'panel', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Panel / switchboard installation (average)', unit: 'each', mh: 16 },
  { id: 'swgr-lv', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'LV switchgear, per panel', unit: 'each', mh: 12 },
  { id: 'swgr-mv', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'MV switchgear, per panel', unit: 'each', mh: 24 },
  { id: 'mcc', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'MCC, per vertical section', unit: 'each', mh: 10 },
  { id: 'motor-conn-s', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Motor connection, up to 75 kW', unit: 'each', mh: 4 },
  { id: 'light', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Light fixture installation', unit: 'each', mh: 1.5 },
  { id: 'ht-cable', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'Electrical heat tracing cable', unit: 'm', mh: 0.25 },
  { id: 'cp-bed', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'CP impressed-current anode bed', unit: 'each', mh: 40 },
  { id: 'cp-tr', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'CP transformer-rectifier', unit: 'each', mh: 24 },
  { id: 'cp-tp', sector: 'Oil & gas (EPCM)', cat: 'Electrical', name: 'CP test point', unit: 'each', mh: 4 },
  // Instrumentation & control
  { id: 'instr', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Field instrument installation (average)', unit: 'each', mh: 4 },
  { id: 'ins-pt', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Pressure transmitter / switch', unit: 'each', mh: 4 },
  { id: 'ins-dpt', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Differential pressure / flow transmitter', unit: 'each', mh: 6 },
  { id: 'ins-lt', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Level transmitter (DP / radar)', unit: 'each', mh: 8 },
  { id: 'ins-te', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Temperature element with thermowell', unit: 'each', mh: 3 },
  { id: 'ins-pg', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Pressure gauge', unit: 'each', mh: 1.5 },
  { id: 'ins-fm-s', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Inline flowmeter, up to 4"', unit: 'each', mh: 8 },
  { id: 'cv-2', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Control valve, 2" (install and hook-up)', unit: 'each', mh: 4 },
  { id: 'cv-4', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Control valve, 4" (install and hook-up)', unit: 'each', mh: 7 },
  { id: 'cv-8', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Control valve, 8" (install and hook-up)', unit: 'each', mh: 14 },
  { id: 'cv-12', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Control valve, 12" (install and hook-up)', unit: 'each', mh: 22 },
  { id: 'analyser', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Process analyser', unit: 'each', mh: 24 },
  { id: 'tubing', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Impulse tubing, SS, 1/2"', unit: 'm', mh: 0.8 },
  { id: 'icable', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Instrument cable, single pair / triad', unit: 'm', mh: 0.05 },
  { id: 'icable-mc', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Instrument multicore cable', unit: 'm', mh: 0.12 },
  { id: 'ijb', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Instrument junction box', unit: 'each', mh: 6 },
  { id: 'iterm', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Instrument termination, per core', unit: 'each', mh: 0.2 },
  { id: 'dcs-cab', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'DCS system cabinet', unit: 'each', mh: 24 },
  { id: 'sis-cab', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'SIS / ESD cabinet', unit: 'each', mh: 24 },
  { id: 'calib', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Instrument bench calibration', unit: 'each', mh: 2 },
  { id: 'loop', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Loop check', unit: 'loop', mh: 3 },
  { id: 'fg-gas', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Gas detector', unit: 'each', mh: 3 },
  { id: 'fg-flame', sector: 'Oil & gas (EPCM)', cat: 'Instrumentation & control', name: 'Flame detector', unit: 'each', mh: 4 },
  // Insulation
  { id: 'insul', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Pipe insulation with cladding (average)', unit: 'm', mh: 0.8 },
  { id: 'ins-hot-2', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Hot insulation with cladding, 2" pipe', unit: 'm', mh: 0.5 },
  { id: 'ins-hot-4', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Hot insulation with cladding, 4" pipe', unit: 'm', mh: 0.7 },
  { id: 'ins-hot-8', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Hot insulation with cladding, 8" pipe', unit: 'm', mh: 1.1 },
  { id: 'ins-hot-12', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Hot insulation with cladding, 12" pipe', unit: 'm', mh: 1.5 },
  { id: 'ins-hot-24', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Hot insulation with cladding, 24" pipe', unit: 'm', mh: 2.6 },
  { id: 'ins-cold-2', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Cold insulation with vapour barrier, 2" pipe', unit: 'm', mh: 0.9 },
  { id: 'ins-cold-4', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Cold insulation with vapour barrier, 4" pipe', unit: 'm', mh: 1.3 },
  { id: 'ins-cold-8', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Cold insulation with vapour barrier, 8" pipe', unit: 'm', mh: 2 },
  { id: 'ins-cold-12', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Cold insulation with vapour barrier, 12" pipe', unit: 'm', mh: 2.7 },
  { id: 'ins-cold-24', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Cold insulation with vapour barrier, 24" pipe', unit: 'm', mh: 4.7 },
  { id: 'ins-eq-hot', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Equipment hot insulation', unit: 'm²', mh: 1.2 },
  { id: 'ins-eq-cold', sector: 'Oil & gas (EPCM)', cat: 'Insulation', name: 'Equipment cold insulation', unit: 'm²', mh: 2.2 },
  // Painting & coating
  { id: 'blast', sector: 'Oil & gas (EPCM)', cat: 'Painting & coating', name: 'Abrasive blasting to Sa 2.5', unit: 'm²', mh: 0.25 },
  { id: 'coat-shop', sector: 'Oil & gas (EPCM)', cat: 'Painting & coating', name: 'Three-coat system, shop', unit: 'm²', mh: 0.4 },
  { id: 'coat-field', sector: 'Oil & gas (EPCM)', cat: 'Painting & coating', name: 'Three-coat system, field incl. surface prep', unit: 'm²', mh: 0.7 },
  { id: 'coat-touchup', sector: 'Oil & gas (EPCM)', cat: 'Painting & coating', name: 'Field touch-up of shop coating', unit: 'm²', mh: 0.5 },
  { id: 'coat-pipe-s', sector: 'Oil & gas (EPCM)', cat: 'Painting & coating', name: 'Pipe painting, up to 4"', unit: 'm', mh: 0.15 },
  { id: 'galv-touchup', sector: 'Oil & gas (EPCM)', cat: 'Painting & coating', name: 'Galvanising touch-up (zinc-rich)', unit: 'm²', mh: 0.5 },
  { id: 'tsa', sector: 'Oil & gas (EPCM)', cat: 'Painting & coating', name: 'Thermal-sprayed aluminium (TSA)', unit: 'm²', mh: 1 },
  // Fireproofing
  { id: 'fp-cem-25', sector: 'Oil & gas (EPCM)', cat: 'Fireproofing', name: 'Cementitious fireproofing, 25 mm', unit: 'm²', mh: 1.2 },
  { id: 'fp-cem-50', sector: 'Oil & gas (EPCM)', cat: 'Fireproofing', name: 'Cementitious fireproofing, 50 mm', unit: 'm²', mh: 1.8 },
  { id: 'fp-int-thin', sector: 'Oil & gas (EPCM)', cat: 'Fireproofing', name: 'Intumescent, thin-film', unit: 'm²', mh: 0.8 },
  { id: 'fp-int-epoxy', sector: 'Oil & gas (EPCM)', cat: 'Fireproofing', name: 'Epoxy intumescent (hydrocarbon fire)', unit: 'm²', mh: 1.2 },
  { id: 'fp-concrete', sector: 'Oil & gas (EPCM)', cat: 'Fireproofing', name: 'Concrete encasement fireproofing', unit: 'm³', mh: 20 },
  // Scaffolding
  { id: 'scaf-erect', sector: 'Oil & gas (EPCM)', cat: 'Scaffolding', name: 'Scaffold erection, system', unit: 'm³', mh: 0.12 },
  { id: 'scaf-dism', sector: 'Oil & gas (EPCM)', cat: 'Scaffolding', name: 'Scaffold dismantling, system', unit: 'm³', mh: 0.06 },
  { id: 'scaf-tube', sector: 'Oil & gas (EPCM)', cat: 'Scaffolding', name: 'Scaffold, tube and clamp, erect and dismantle', unit: 'm³', mh: 0.25 },
  { id: 'scaf-hang', sector: 'Oil & gas (EPCM)', cat: 'Scaffolding', name: 'Hanging / cantilever scaffold', unit: 'm²', mh: 1.5 },
  // Civil & foundations
  { id: 'og-clear', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Site clearing and grubbing', unit: 'm²', mh: 0.02 },
  { id: 'og-exc-bulk', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Bulk excavation, mechanical', unit: 'm³', mh: 0.1 },
  { id: 'pile-bored-600', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Bored pile, 600 mm diameter', unit: 'm', mh: 1.2 },
  { id: 'pile-bored-1000', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Bored pile, 1000 mm diameter', unit: 'm', mh: 2 },
  { id: 'pile-driven-pc', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Driven precast concrete pile', unit: 'm', mh: 0.6 },
  { id: 'og-blinding', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Blinding / lean concrete', unit: 'm³', mh: 3 },
  { id: 'og-form-fdn', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Formwork, foundations', unit: 'm²', mh: 1.6 },
  { id: 'og-rebar', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Reinforcement, foundations', unit: 'MT', mh: 22 },
  { id: 'conc-eq-fdn', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Concrete, equipment foundation', unit: 'm³', mh: 5 },
  { id: 'conc-rack', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Concrete, pipe rack column / foundation', unit: 'm³', mh: 8 },
  { id: 'sleeper', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Precast pipe sleeper, set in place', unit: 'm', mh: 1.5 },
  { id: 'anchor-bolt', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Anchor bolt setting', unit: 'each', mh: 1.5 },
  { id: 'grout-cem', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Cementitious grout under baseplate', unit: 'm³', mh: 30 },
  { id: 'grout-epoxy', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Epoxy grout under machinery', unit: 'm³', mh: 60 },
  { id: 'og-paving', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Concrete paving, 150 mm', unit: 'm²', mh: 0.6 },
  { id: 'bund-wall', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Bund / dyke wall, concrete', unit: 'm³', mh: 9 },
  { id: 'og-fence', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Chain-link security fence', unit: 'm', mh: 1.2 },
  { id: 'og-manhole', sector: 'Oil & gas (EPCM)', cat: 'Civil & foundations', name: 'Manhole / sump pit', unit: 'each', mh: 24 },
  // Structural steel
  { id: 'og-fab-light', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Steel fabrication, light (<30 kg/m)', unit: 'MT', mh: 45 },
  { id: 'og-fab-med', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Steel fabrication, medium (30 to 75 kg/m)', unit: 'MT', mh: 35 },
  { id: 'og-fab-heavy', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Steel fabrication, heavy (>75 kg/m)', unit: 'MT', mh: 25 },
  { id: 'og-erect-light', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Steel erection, light', unit: 'MT', mh: 28 },
  { id: 'og-erect-med', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Steel erection, medium', unit: 'MT', mh: 20 },
  { id: 'og-erect-heavy', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Steel erection, heavy', unit: 'MT', mh: 14 },
  { id: 'rack-steel', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Pipe rack steel erection', unit: 'MT', mh: 18 },
  { id: 'og-misc-steel', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Miscellaneous steel (brackets, platforms)', unit: 'MT', mh: 60 },
  { id: 'og-grating', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Grating installation', unit: 'm²', mh: 0.8 },
  { id: 'og-handrail', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Handrail and toe plate', unit: 'm', mh: 1 },
  { id: 'og-stairs', sector: 'Oil & gas (EPCM)', cat: 'Structural steel', name: 'Stairs and stair towers', unit: 'MT', mh: 50 },
  // Cross-country pipelines
  { id: 'pl-row', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'ROW clearing and grading', unit: 'km', mh: 300 },
  { id: 'pl-string', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Pipe stringing', unit: 'joint', mh: 0.8 },
  { id: 'pl-weld-8', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Mainline weld, 8" (spread crew)', unit: 'joint', mh: 6 },
  { id: 'pl-weld-12', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Mainline weld, 12" (spread crew)', unit: 'joint', mh: 9 },
  { id: 'pl-weld-16', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Mainline weld, 16" (spread crew)', unit: 'joint', mh: 12 },
  { id: 'pl-weld-24', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Mainline weld, 24" (spread crew)', unit: 'joint', mh: 18 },
  { id: 'pl-weld-36', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Mainline weld, 36" (spread crew)', unit: 'joint', mh: 30 },
  { id: 'pl-weld-48', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Mainline weld, 48" (spread crew)', unit: 'joint', mh: 42 },
  { id: 'pl-aut', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'AUT of mainline weld', unit: 'joint', mh: 1.5 },
  { id: 'pl-fjc-s', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Field joint coating (HSS / FBE)', unit: 'joint', mh: 2 },
  { id: 'pl-trench', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Trenching, mechanical', unit: 'm', mh: 0.25 },
  { id: 'pl-lower', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Lowering-in', unit: 'm', mh: 0.15 },
  { id: 'pl-backfill', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Backfill', unit: 'm', mh: 0.15 },
  { id: 'pl-reinstate', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'ROW reinstatement', unit: 'km', mh: 200 },
  { id: 'pl-hdd-s', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'HDD crossing, up to 24"', unit: 'm', mh: 4 },
  { id: 'pl-road', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Road crossing, auger bore with casing', unit: 'each', mh: 120 },
  { id: 'pl-river', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'River crossing, open-cut', unit: 'm', mh: 15 },
  { id: 'pl-tiein', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Tie-in weld', unit: 'each', mh: 40 },
  { id: 'pl-hydro', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Hydrotest', unit: 'km', mh: 60 },
  { id: 'pl-cp-tp', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Pipeline CP test point', unit: 'each', mh: 6 },
  { id: 'pl-bvs', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Block valve station', unit: 'each', mh: 400 },
  { id: 'pl-trap', sector: 'Oil & gas (EPCM)', cat: 'Cross-country pipelines', name: 'Pig launcher / receiver', unit: 'each', mh: 300 },
  // Pre-commissioning & commissioning
  { id: 'pc-walkdown', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'System walkdown and punch listing', unit: 'system', mh: 16 },
  { id: 'pc-punch', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Punch-list clearance', unit: 'system', mh: 24 },
  { id: 'pc-motor-s', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Motor solo run, LV', unit: 'each', mh: 4 },
  { id: 'pc-motor-l', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Motor solo run, HV', unit: 'each', mh: 8 },
  { id: 'pc-loop-func', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Loop function test', unit: 'loop', mh: 2 },
  { id: 'pc-ce', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Cause and effect / SIF test', unit: 'each', mh: 6 },
  { id: 'pc-io', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'DCS / SIS I/O commissioning', unit: 'point', mh: 0.5 },
  { id: 'pc-leak', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Nitrogen / helium leak test', unit: 'system', mh: 24 },
  { id: 'pc-dry', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Drying and inerting', unit: 'system', mh: 40 },
  { id: 'pc-package', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Package unit commissioning', unit: 'module', mh: 80 },
  { id: 'pc-comp-run', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Compressor run-in', unit: 'each', mh: 200 },
  { id: 'pc-pssr', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Pre-startup safety review', unit: 'each', mh: 24 },
  { id: 'pc-perf', sector: 'Oil & gas (EPCM)', cat: 'Pre-commissioning & commissioning', name: 'Performance test run', unit: 'system', mh: 160 },

  // ===== Engineering & procurement =====
  // Engineering deliverables
  { id: 'eng-drawing', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Engineering drawing, A1 sheet (general)', unit: 'sheet', mh: 40 },
  { id: 'doc-review', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Document review and comments', unit: 'doc', mh: 4 },
  { id: 'calc', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Design calculation note', unit: 'doc', mh: 24 },
  { id: 'boq', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Bill of quantities preparation', unit: 'sheet', mh: 3 },
  { id: 'eng-pfd', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Process flow diagram (PFD)', unit: 'sheet', mh: 80 },
  { id: 'eng-pid', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'P&ID, new sheet', unit: 'sheet', mh: 120 },
  { id: 'eng-plot', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Plot plan', unit: 'sheet', mh: 120 },
  { id: 'eng-ga', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Piping GA drawing', unit: 'sheet', mh: 80 },
  { id: 'eng-iso', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Isometric, model-extracted', unit: 'sheet', mh: 3 },
  { id: 'eng-iso-man', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Isometric, manual drafting', unit: 'sheet', mh: 8 },
  { id: 'eng-stress', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Pipe stress analysis, critical line', unit: 'each', mh: 16 },
  { id: 'eng-3d', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: '3D model, per plant area', unit: 'each', mh: 400 },
  { id: 'eng-mto', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Material take-off (MTO), per area', unit: 'doc', mh: 40 },
  { id: 'eng-ds-proc', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Process datasheet', unit: 'doc', mh: 12 },
  { id: 'eng-ds-mech', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Mechanical equipment datasheet', unit: 'doc', mh: 16 },
  { id: 'eng-ds-inst', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Instrument datasheet', unit: 'doc', mh: 4 },
  { id: 'eng-spec', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Technical specification', unit: 'doc', mh: 80 },
  { id: 'eng-struct', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Structural steel drawing', unit: 'sheet', mh: 40 },
  { id: 'eng-fdn', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Foundation / civil drawing', unit: 'sheet', mh: 30 },
  { id: 'eng-sld', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Single-line diagram (SLD)', unit: 'sheet', mh: 40 },
  { id: 'eng-cable-sch', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Cable schedule', unit: 'sheet', mh: 4 },
  { id: 'eng-tray-layout', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Cable tray / lighting layout', unit: 'sheet', mh: 40 },
  { id: 'eng-inst-index', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Instrument index, per 100 tags', unit: 'doc', mh: 16 },
  { id: 'eng-io-list', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'I/O list', unit: 'sheet', mh: 6 },
  { id: 'eng-loop-dia', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Loop diagram', unit: 'sheet', mh: 3 },
  { id: 'eng-hookup', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Instrument hook-up drawing', unit: 'sheet', mh: 8 },
  { id: 'eng-ce-chart', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Cause and effect chart', unit: 'sheet', mh: 16 },
  { id: 'eng-narrative', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'Control narrative', unit: 'doc', mh: 60 },
  { id: 'eng-hazop', sector: 'Engineering & procurement', cat: 'Engineering deliverables', name: 'HAZOP, per node', unit: 'each', mh: 12 },
  // Procurement & inspection
  { id: 'proc-mr', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'Material requisition', unit: 'doc', mh: 16 },
  { id: 'proc-rfq', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'RFQ package', unit: 'set', mh: 24 },
  { id: 'proc-tbe', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'Technical bid evaluation', unit: 'doc', mh: 32 },
  { id: 'proc-cbe', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'Commercial bid evaluation', unit: 'doc', mh: 8 },
  { id: 'proc-po', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'Purchase order issue', unit: 'each', mh: 16 },
  { id: 'proc-vdr', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'Vendor document review', unit: 'doc', mh: 3 },
  { id: 'proc-expedite', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'Expediting, per PO-month', unit: 'each', mh: 4 },
  { id: 'proc-insp', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'Inspection visit', unit: 'each', mh: 12 },
  { id: 'proc-fat', sector: 'Engineering & procurement', cat: 'Procurement & inspection', name: 'Factory acceptance test (FAT)', unit: 'each', mh: 40 },
  // Software & IT
  { id: 'fp', sector: 'Engineering & procurement', cat: 'Software & IT', name: 'Development effort per function point', unit: 'FP', mh: 8 },
  { id: 'screen', sector: 'Engineering & procurement', cat: 'Software & IT', name: 'UI screen, medium complexity', unit: 'screen', mh: 16 },
  { id: 'api', sector: 'Engineering & procurement', cat: 'Software & IT', name: 'API endpoint with tests', unit: 'endpoint', mh: 12 },
  { id: 'tc-write', sector: 'Engineering & procurement', cat: 'Software & IT', name: 'Test case writing', unit: 'test case', mh: 1 },
  { id: 'tc-run', sector: 'Engineering & procurement', cat: 'Software & IT', name: 'Test case execution', unit: 'test case', mh: 0.5 },
  { id: 'doc-page', sector: 'Engineering & procurement', cat: 'Software & IT', name: 'Technical documentation', unit: 'page', mh: 2 },

  // ===== Power & renewables =====
  // Solar PV
  { id: 'pv-pile', sector: 'Power & renewables', cat: 'Solar PV', name: 'Driven pile / post for PV structure', unit: 'each', mh: 0.4 },
  { id: 'pv-struct', sector: 'Power & renewables', cat: 'Solar PV', name: 'Fixed-tilt structure assembly', unit: 'MT', mh: 25 },
  { id: 'pv-tracker', sector: 'Power & renewables', cat: 'Solar PV', name: 'Single-axis tracker row assembly', unit: 'each', mh: 16 },
  { id: 'pv-module', sector: 'Power & renewables', cat: 'Solar PV', name: 'PV module installation', unit: 'each', mh: 0.15 },
  { id: 'pv-string', sector: 'Power & renewables', cat: 'Solar PV', name: 'DC string cabling', unit: 'm', mh: 0.03 },
  { id: 'pv-trench', sector: 'Power & renewables', cat: 'Solar PV', name: 'Cable trench, excavate and backfill', unit: 'm', mh: 0.4 },
  { id: 'pv-cbox', sector: 'Power & renewables', cat: 'Solar PV', name: 'Combiner box', unit: 'each', mh: 4 },
  { id: 'pv-inv-str', sector: 'Power & renewables', cat: 'Solar PV', name: 'String inverter', unit: 'each', mh: 4 },
  { id: 'pv-inv-cen', sector: 'Power & renewables', cat: 'Solar PV', name: 'Central inverter / inverter skid', unit: 'each', mh: 60 },
  { id: 'pv-tx', sector: 'Power & renewables', cat: 'Solar PV', name: 'MV transformer, 2.5 to 4 MVA', unit: 'each', mh: 60 },
  { id: 'pv-scada', sector: 'Power & renewables', cat: 'Solar PV', name: 'Plant SCADA and monitoring', unit: 'system', mh: 80 },
  { id: 'pv-test', sector: 'Power & renewables', cat: 'Solar PV', name: 'String test (Voc, IV curve)', unit: 'each', mh: 0.4 },
  // Wind
  { id: 'wtg-rebar', sector: 'Power & renewables', cat: 'Wind', name: 'WTG foundation reinforcement', unit: 'MT', mh: 30 },
  { id: 'wtg-conc', sector: 'Power & renewables', cat: 'Wind', name: 'WTG foundation concrete, pumped', unit: 'm³', mh: 2 },
  { id: 'wtg-cage', sector: 'Power & renewables', cat: 'Wind', name: 'Anchor cage assembly', unit: 'each', mh: 120 },
  { id: 'wtg-tower', sector: 'Power & renewables', cat: 'Wind', name: 'Tower section erection', unit: 'each', mh: 60 },
  { id: 'wtg-nacelle', sector: 'Power & renewables', cat: 'Wind', name: 'Nacelle lift', unit: 'each', mh: 100 },
  { id: 'wtg-blades', sector: 'Power & renewables', cat: 'Wind', name: 'Rotor / blade set installation', unit: 'set', mh: 120 },
  { id: 'wtg-erect', sector: 'Power & renewables', cat: 'Wind', name: 'WTG erection complete, 3 to 5 MW', unit: 'each', mh: 600 },
  { id: 'wtg-cable', sector: 'Power & renewables', cat: 'Wind', name: 'Collector cable, 33 kV', unit: 'm', mh: 0.2 },
  { id: 'wtg-comm', sector: 'Power & renewables', cat: 'Wind', name: 'WTG commissioning', unit: 'each', mh: 200 },
  // Transmission & substations
  { id: 'tl-fdn', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Tower foundation concrete', unit: 'm³', mh: 6 },
  { id: 'tl-tower', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Lattice tower erection', unit: 'MT', mh: 30 },
  { id: 'tl-string', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Conductor stringing, per circuit', unit: 'km', mh: 400 },
  { id: 'tl-opgw', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'OPGW / earth wire stringing', unit: 'km', mh: 120 },
  { id: 'tl-insulator', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Insulator string', unit: 'each', mh: 2 },
  { id: 'tl-earth', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Tower earthing', unit: 'each', mh: 6 },
  { id: 'ss-cb', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Circuit breaker, 132 kV', unit: 'each', mh: 40 },
  { id: 'ss-iso', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Disconnector / isolator', unit: 'each', mh: 24 },
  { id: 'ss-ctvt', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'CT / VT', unit: 'each', mh: 8 },
  { id: 'ss-ptx', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Power transformer, 100 MVA', unit: 'each', mh: 600 },
  { id: 'ss-gantry', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Gantry / equipment support steel', unit: 'MT', mh: 30 },
  { id: 'ss-bus', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Busbar / tubular bus', unit: 'm', mh: 1.5 },
  { id: 'ss-crp', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Control and relay panel', unit: 'each', mh: 24 },
  { id: 'ss-mat', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Substation earth mat conductor', unit: 'm', mh: 0.4 },
  { id: 'ss-prot-test', sector: 'Power & renewables', cat: 'Transmission & substations', name: 'Protection testing, per bay', unit: 'each', mh: 40 },

  // ===== Buildings & infrastructure =====
  // Building MEP
  { id: 'mep-pipe-s', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Water supply pipe, up to 1"', unit: 'm', mh: 0.6 },
  { id: 'mep-pipe-l', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Water supply pipe, 1-1/2" to 4"', unit: 'm', mh: 1 },
  { id: 'mep-drain', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'uPVC drainage pipe', unit: 'm', mh: 0.5 },
  { id: 'mep-wc', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'WC with cistern', unit: 'each', mh: 4 },
  { id: 'mep-basin', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Wash basin with taps', unit: 'each', mh: 3 },
  { id: 'mep-shower', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Shower set', unit: 'each', mh: 4 },
  { id: 'mep-pump', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Booster pump set', unit: 'each', mh: 16 },
  { id: 'duct', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'HVAC ducting, fabricate and install', unit: 'm²', mh: 1.2 },
  { id: 'mep-duct-kg', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Galvanised ductwork', unit: 'kg', mh: 0.12 },
  { id: 'mep-diffuser', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Diffuser / grille', unit: 'each', mh: 1 },
  { id: 'mep-fcu', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Fan coil unit', unit: 'each', mh: 6 },
  { id: 'mep-split', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Split AC unit', unit: 'each', mh: 6 },
  { id: 'mep-ahu-s', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'AHU, up to 10,000 m³/h', unit: 'each', mh: 24 },
  { id: 'mep-ahu-l', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'AHU, above 10,000 m³/h', unit: 'each', mh: 60 },
  { id: 'mep-chiller', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Chiller, 300 to 500 TR', unit: 'each', mh: 200 },
  { id: 'mep-chw', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Chilled water pipe, 2" to 6"', unit: 'm', mh: 1.5 },
  { id: 'mep-spr-pipe', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Sprinkler pipe', unit: 'm', mh: 0.8 },
  { id: 'mep-spr-head', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Sprinkler head', unit: 'each', mh: 0.8 },
  { id: 'mep-firepump', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Fire pump set', unit: 'each', mh: 60 },
  { id: 'mep-fa-det', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Fire alarm detector', unit: 'each', mh: 1 },
  { id: 'mep-light-pt', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Lighting point wiring', unit: 'point', mh: 1.2 },
  { id: 'mep-power-pt', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Power socket point wiring', unit: 'point', mh: 1.5 },
  { id: 'mep-bms', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'BMS point', unit: 'point', mh: 1.5 },
  { id: 'mep-lift', sector: 'Buildings & infrastructure', cat: 'Building MEP', name: 'Passenger lift, up to 10 stops', unit: 'each', mh: 400 },
  // Roads & drainage
  { id: 'rd-subgrade', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Subgrade preparation', unit: 'm²', mh: 0.04 },
  { id: 'rd-gsb', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Granular sub-base', unit: 'm³', mh: 0.3 },
  { id: 'rd-wmm', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Wet-mix macadam base', unit: 'm³', mh: 0.4 },
  { id: 'rd-asphalt', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Asphalt paving', unit: 'MT', mh: 0.3 },
  { id: 'rd-pqc', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Concrete pavement (PQC)', unit: 'm³', mh: 3 },
  { id: 'rd-kerb', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Precast kerb', unit: 'm', mh: 0.8 },
  { id: 'rd-footpath', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Footpath paver blocks', unit: 'm²', mh: 1 },
  { id: 'rd-storm', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Storm drain pipe, 600 mm', unit: 'm', mh: 2 },
  { id: 'rd-culvert', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Box culvert', unit: 'm³', mh: 10 },
  { id: 'rd-manhole', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Drainage manhole', unit: 'each', mh: 24 },
  { id: 'rd-marking', sector: 'Buildings & infrastructure', cat: 'Roads & drainage', name: 'Road marking, thermoplastic', unit: 'm²', mh: 0.15 },
  // Interiors & fit-out
  { id: 'ceiling', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Gypsum false ceiling', unit: 'm²', mh: 0.8 },
  { id: 'partition', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Drywall partition', unit: 'm²', mh: 1.2 },
  { id: 'door', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Door installation with hardware', unit: 'each', mh: 4 },
  { id: 'int-carpet', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Carpet tiles', unit: 'm²', mh: 0.3 },
  { id: 'int-vinyl', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Vinyl flooring', unit: 'm²', mh: 0.4 },
  { id: 'int-raised', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Raised access floor', unit: 'm²', mh: 0.6 },
  { id: 'int-glass', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Glazed partition', unit: 'm²', mh: 2 },
  { id: 'int-joinery', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Built-in joinery / cabinets', unit: 'm', mh: 4 },
  { id: 'int-paint', sector: 'Buildings & infrastructure', cat: 'Interiors & fit-out', name: 'Interior emulsion painting, 2 coats', unit: 'm²', mh: 0.2 },

  // ===== General construction =====
  // Earthworks
  { id: 'exc-man', sector: 'General construction', cat: 'Earthworks', name: 'Excavation, manual, ordinary soil', unit: 'm³', mh: 2.5 },
  { id: 'exc-mech', sector: 'General construction', cat: 'Earthworks', name: 'Excavation, mechanical (operator + helper)', unit: 'm³', mh: 0.15 },
  { id: 'backfill', sector: 'General construction', cat: 'Earthworks', name: 'Backfilling and compaction in layers', unit: 'm³', mh: 0.8 },
  // Concrete
  { id: 'pcc', sector: 'General construction', cat: 'Concrete', name: 'Plain cement concrete (PCC), mix, place, compact', unit: 'm³', mh: 6 },
  { id: 'rcc', sector: 'General construction', cat: 'Concrete', name: 'Reinforced concrete, place and compact (manual)', unit: 'm³', mh: 8 },
  { id: 'rcc-pump', sector: 'General construction', cat: 'Concrete', name: 'Reinforced concrete, pumped', unit: 'm³', mh: 2.5 },
  { id: 'formwork', sector: 'General construction', cat: 'Concrete', name: 'Formwork, fabricate, erect and strip', unit: 'm²', mh: 1.8 },
  { id: 'rebar', sector: 'General construction', cat: 'Concrete', name: 'Reinforcement, cut, bend and fix', unit: 'MT', mh: 25 },
  // Masonry & finishes
  { id: 'brick-230', sector: 'General construction', cat: 'Masonry & finishes', name: 'Brick masonry, 230 mm wall', unit: 'm³', mh: 15 },
  { id: 'block-200', sector: 'General construction', cat: 'Masonry & finishes', name: 'Concrete block masonry, 200 mm', unit: 'm²', mh: 1.4 },
  { id: 'plaster', sector: 'General construction', cat: 'Masonry & finishes', name: 'Cement plaster, 12 mm', unit: 'm²', mh: 0.6 },
  { id: 'floor-vdf', sector: 'General construction', cat: 'Masonry & finishes', name: 'Industrial floor (VDF) finishing', unit: 'm²', mh: 0.35 },
  { id: 'tile', sector: 'General construction', cat: 'Masonry & finishes', name: 'Floor tiling with bedding', unit: 'm²', mh: 1 },
  { id: 'paint', sector: 'General construction', cat: 'Masonry & finishes', name: 'Painting, primer + 2 coats', unit: 'm²', mh: 0.25 },
  { id: 'waterproof', sector: 'General construction', cat: 'Masonry & finishes', name: 'Waterproofing membrane', unit: 'm²', mh: 0.4 },
  // Structural steel
  { id: 'steel-fab', sector: 'General construction', cat: 'Structural steel', name: 'Steel fabrication (shop)', unit: 'MT', mh: 35 },
  { id: 'steel-erect', sector: 'General construction', cat: 'Structural steel', name: 'Steel erection and bolting', unit: 'MT', mh: 20 },
  { id: 'steel-paint', sector: 'General construction', cat: 'Structural steel', name: 'Blasting and painting of steel', unit: 'MT', mh: 8 },
  { id: 'roof-sheet', sector: 'General construction', cat: 'Structural steel', name: 'Roof / wall sheeting', unit: 'm²', mh: 0.35 },
  { id: 'grating', sector: 'General construction', cat: 'Structural steel', name: 'Grating and handrail installation', unit: 'm²', mh: 1.2 },
];
